ekf_node:
  ros__parameters:
    frequency: 30
    two_d_mode: true

    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # GPS from NavSat transform
    odom0: /gps/odom
    odom0_config: [true, true, false,     # x, y, z
                   false, false, true,    # roll, pitch, yaw   <- yaw from GPS+IMU
                   true, true, false,     # vx, vy, vz         <- GPS velocity
                   false, false, false,   # vroll, vpitch, vyaw
                   false, false, false]   # ax, ay, az
    odom0_queue_size: 10
    odom0_differential: false

    # IMU (orientation + angular velocity)
    imu0: /imu/data
    imu0_config: [false, false, false,   # x, y, z (IMU doesn't give pos)
                  true, true, true,      # roll, pitch, yaw
                  false, false, false,   # vx, vy, vz  (IMU does NOT give velocity)
                  true, true, true,      # vroll, vpitch, vyaw
                  false, false, false]
    imu0_remove_gravitational_acceleration: true

