frequency: 10
delay: 0.0

# Frames
world_frame: map
base_link_frame: base_link
odom_frame: odom

# Topics
imu_topic: /imu/data
gps_topic: /fix
odometry_topic: /odometry/filtered
# This will be published by navsat_transform_node
gps_odom_topic: /odometry/gps

# Behavior
magnetic_declination_radians: 0.0
yaw_offset: 0.0
broadcast_utm_transform: true
broadcast_utm_transform_as_parent_frame: true
zero_altitude: true
publish_filtered_gps: true
use_odometry_yaw: false
wait_for_datum: false

