# Static transforms between base_link and sensors

transforms:
  - frame_id: base_link
    child_frame_id: lidar_link
    translation: [0.0, 0.0, 0.133]    #  13.3 cm above center on the mount
    rotation_rpy: [0.0, 0.0, -0.0872, 0.9962]   # -10Â° in radians (yaw)

  - frame_id: base_link
    child_frame_id: gps_link
    translation: [-0.04, 0.0, 0.208]    # 20.8 cm above center, sitting on top of the bridge structure
    rotation_rpy: [0.0, 0.0, 0.0]    

  - frame_id: base_link
    child_frame_id: imu_link
    translation: [0.0, 0.0, 0.07]    # 7 cm above center, aproximately where the ESP32 is
    rotation_rpy: [0.0, 0.0, 0.0]   


